### ISSUE TITLE
Failure parsing long option

### ISSUE THREAD

**Issue by robinbowes** [agriffis/pure-getopt#7]
Hi,

I'm seeing a problem handling long options with your getopt function.

I've created the following test case: https://gist.github.com/robinbowes/e3e656736f0421985173091b41f7998b

My goal is to handle an options value containing another option like this: `test.sh --extra "--foo=bar"` but I'm finding that I can't even parse a simple option like this: `test.sh --extra foo`.

This is the output from my test script:
```
$ ./test.sh --extra foo
[ '--extra' 'foo' '--']
$@: --extra foo --
argv: --extra
$1: --extra
$2: foo
$@: --
argv: foo
$1: --
$2: undef
Something went wrong processing command line options
```

It seems that `foo` is being treated as another option rather than being the value for the `--extra` option.

Am I doing something wrong here, or is this a bug?

**Comment by agriffis** [comment]
I think you're doing something wrong, but it's not your fault. The problem is the example is incorrect.

The `for a` should be replaced by `while true` so that shifting options works properly. The problem with `for a` is that it will attempt to handle each item in `$@` individually.

In other words, your `test.sh` should do this:

```
  while true; do
    case $1 in
      -f | --fix)
        _ARGS[fix]=1
        shift
        ;;
      -p | --prompt)
        _ARGS[prompt]=1
        shift
        ;;
      -e | --extra)
        _ARGS[extra]="$2"
        shift 2
        ;;
      --)
        shift
        break
        ;;
      *)
        echo 'Something went wrong processing command line options' >&2
        exit 2
        ;;
    esac
  done
```

Let me know how it goes :smile:

**Comment by agriffis** [comment]
Also, I noticed you have a minor error on this line:

```
  argv=$(getopt -o 'efp:' --long 'extra:,fix,prompt' -- "$@") || return
```

because you want a colon after the `e` instead of the `p`, like this:

```
  argv=$(getopt -o 'e:fp' --long 'extra:,fix,prompt' -- "$@") || return
```

**Comment by robinbowes** [comment]
@agriffis Thanks for this - I shall try that change. I actually decided to use your ghettopts framework as well which is easier and worked just fine!

**Comment by robinbowes** [comment]
Sidenote: I may submit a PR to allow pure-getopts to work under `set -u` at some stage in the future.
